name: Comment2

on:
  issue_comment:
    types: [created, deleted]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Create issue using REST API
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/check-runs \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{"name":"autorun","head_sha":"${{ github.sha }}"}' \
          --fail
