name: Comment2

on:
  issue_comment:
    types: [created, deleted]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"

