name: Comment2

on:
  issue_comment:
    types: [created, deleted]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tools repo
        run: echo $${{ github.event }}

