name: Comment2

on:
  issue_comment:
    types: [created, deleted]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - env:
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          gh workflow run env.yaml

https://github.com/algattik/TestSecrets/pull/3#issuecomment-1055040306

